# Generated by Django 2.2.13 on 2021-12-07 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('jp_name', models.CharField(blank=True, max_length=264, null=True)),
                ('channel', models.URLField(blank=True, unique=True)),
                ('channel_id', models.CharField(blank=True, max_length=264, unique=True)),
                ('slug', models.SlugField()),
                ('twitter', models.URLField(blank=True)),
                ('agency', models.CharField(blank=True, choices=[('Nijisanji', 'NIJISANJI'), ('Hololive', 'HOLOLIVE'), ('Independent', 'INDIE'), ('774 inc.', '774')], max_length=256)),
                ('subgroup', models.CharField(blank=True, choices=[('Hololive First Generation', 'FIRST'), ('Hololive Second Generation', 'SECOND'), ('Hololive Third Generation', 'THIRD'), ('Hololive Fourth Generation', 'FOURTH'), ('Hololive Fifth Generation', 'FIFTH'), ('Hololive Gamers', 'GAMER'), ('Hololive 3D Talent', '3D'), ('Hololive 2D Talent', '2D'), ('INoNaKa MUSIC', 'INoNaKa')], max_length=256)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('romanji_name', models.CharField(blank=True, max_length=264, null=True)),
                ('translated_name', models.CharField(blank=True, max_length=264, null=True)),
                ('original_artist', models.CharField(blank=True, max_length=264, null=True)),
                ('romanji_original_artist', models.CharField(blank=True, max_length=264, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('link', models.URLField(unique=True)),
                ('youtube_id', models.CharField(max_length=264, unique=True)),
                ('date_posted', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('stream_type', models.CharField(blank=True, choices=[('KARAOKE', 'Karaoke Stream'), ('ORIGINAL', 'Original Song'), ('COVER', 'Cover')], max_length=256)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('guest_singers', models.ManyToManyField(blank=True, related_name='guest_singers', to='archive.Singer')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Singer')),
            ],
        ),
        migrations.CreateModel(
            name='StreamTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('timestamp', models.IntegerField(blank=True, help_text='This is the point in seconds at which this song occurs in a stream.', null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Song')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Stream')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='songs',
            field=models.ManyToManyField(blank=True, through='archive.StreamTrack', to='archive.Song'),
        ),
    ]
