# Generated by Django 2.2 on 2020-07-19 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('channel', models.URLField(blank=True)),
                ('channel_id', models.CharField(blank=True, max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('romanji_name', models.CharField(blank=True, max_length=264, null=True)),
                ('translated_name', models.CharField(blank=True, max_length=264, null=True)),
                ('playlist_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('link', models.URLField(blank=True)),
                ('youtube_id', models.CharField(blank=True, max_length=264)),
                ('date_posted', models.DateField(blank=True, default=datetime.datetime(2020, 7, 19, 6, 38, 30, 492006, tzinfo=utc), null=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Idol')),
                ('songs', models.ManyToManyField(blank=True, to='archive.Song')),
            ],
        ),
    ]
