# Generated by Django 2.2 on 2020-07-19 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 19, 6, 38, 46, 238802, tzinfo=utc), null=True),
        ),
    ]
