# Generated by Django 2.2 on 2020-07-19 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200719_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='date_posted',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
