# Generated by Django 2.2 on 2020-07-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20200719_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='jp_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
