# Generated by Django 2.2 on 2020-07-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20200719_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_artist',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
