# Generated by Django 2.2 on 2020-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_song_original_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_artist_jp',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
