# Generated by Django 2.2 on 2020-07-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20200719_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='guest_singers',
            field=models.ManyToManyField(blank=True, related_name='guest_singers', to='archive.Idol'),
        ),
    ]
