# Generated by Django 2.2 on 2020-07-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_stream_guest_singers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='original_song',
            field=models.BooleanField(default=False),
        ),
    ]
