# Generated by Django 2.2.13 on 2020-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20200727_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamtrack',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
