# Generated by Django 2.2.13 on 2020-07-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_auto_20200729_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
