# Generated by Django 2.2.13 on 2020-07-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20200729_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='slug',
            field=models.SlugField(default='owo'),
            preserve_default=False,
        ),
    ]
