# Generated by Django 2.2 on 2020-07-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
