# Generated by Django 2.2 on 2020-07-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_idol_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='group',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
