# Generated by Django 2.2 on 2020-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_idol_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='youtube_id',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
