# Generated by Django 2.2 on 2020-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_auto_20200731_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='group',
            field=models.CharField(blank=True, choices=[('FIRST', 'Hololive First Generation'), ('SECOND', 'Hololive Second Generation'), ('THIRD', 'Hololive Third Generation'), ('FOURTH', 'Hololive Fourth Generation'), ('GAMER', 'Hololive Gamers')], max_length=256),
        ),
    ]
