# Generated by Django 2.2 on 2020-08-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_auto_20200731_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='group',
            field=models.CharField(blank=True, choices=[('Hololive First Generation', 'FIRST'), ('Hololive Second Generation', 'SECOND'), ('Hololive Third Generation', 'THIRD'), ('Hololive Fourth Generation', 'FOURTH'), ('Hololive Gamers', 'GAMER'), ('Hololive 3D Talent', '3D'), ('Hololive 2D Talent', '2D'), ('INoNaKa MUSIC', 'INoNaKa')], max_length=256),
        ),
        migrations.AlterField(
            model_name='stream',
            name='original_song',
            field=models.CharField(blank=True, choices=[('Stream', 'STREAM'), ('Original Song', 'ORIGINAL'), ('Cover', 'COVER')], max_length=256),
        ),
    ]
