# Generated by Django 2.2 on 2020-08-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0025_auto_20200803_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='original_song',
            new_name='stream_type',
        ),
    ]
